/*
DEVELOPED BY SAMIRA ALVES LUCIO DIA
DATE: 01/07/2020
GOAL: REPORT DEVELOPED TO CALCULATE THE TIME BETWEEN PATIENT CARE DURIN CHILD EMERGENCY AND
PREPARED TO BE INSERT INTO MV'S BU SYSTEM
*/

SELECT
       DOC.CD_REGISTRO_DOCUMENTO 
      ,DOC.CD_ATENDIMENTO 
      ,ATENDIME.CD_ORI_ATE
      ,ORI_ATE.DS_ORI_ATE
      ,DOC.NM_USUARIO
      ,DOC.CD_DOCUMENTO 
      ,DOCUMENTO.DS_DOCUMENTO
      ,to_char(DOC.DT_REGISTRO,'DD/MM/YYYY') DIA
      ,to_char(DOC.DT_REGISTRO,'HH24:MI:SS') HORARIO 
       --,SUBSTR(TO_CHAR(DOC.DT_REGISTRO),10,20) HORARIO 
      ,CORES.STATUS
         
FROM REGISTRO_DOCUMENTO DOC
INNER JOIN ATENDIME ATENDIME
  ON ATENDIME.CD_ATENDIMENTO = DOC.CD_ATENDIMENTO
INNER JOIN DOCUMENTO DOCUMENTO
  ON DOCUMENTO.CD_DOCUMENTO = DOC.CD_DOCUMENTO
INNER JOIN ORI_ATE ORI_ATE
  ON ORI_ATE.CD_ORI_ATE = ATENDIME.CD_ORI_ATE
INNER JOIN VDIC_TRIAGEM_INFANTIL_COR CORES
  ON CORES.CD_ATENDIMENTO = DOC.CD_ATENDIMENTO
WHERE TO_CHAR(ATENDIME.DT_ATENDIMENTO,'DD/MM/YYYY') BETWEEN  #TaubateDataInicial#  AND #TaubateFinal#
AND ATENDIME.CD_ORI_ATE = '11'
AND DOC.SN_IMPRESSO NOT in ('C')
AND doc.cd_documento in ('180','157','115')
ORDER BY ATENDIME.CD_ATENDIMENTO,
         CORES.STATUS,
         HORARIO