/*
DEVELOPED BY SAMIRA ALVES LUCIO DIA
DATE: 01/07/2020
GOAL: SELECT STRUCTER DEVELOPED TO MAKE A SEARCH E VERIFY INTO DOCUMENT TRIAGEM INFANTIL BEFORE VDIC CREATION, SO IN THE 
REPORT FLUXO ATENDIMENTO WE ARE ABLE TO KNOW EACH PACIENT PRIORITY CLASSIFICATION
*/
SELECT 
       
      DOC.CD_REGISTRO_DOCUMENTO "REGISTRO"
      ,DOC.CD_ATENDIMENTO "ATENDIMENTO"
      ,ATENDIME.CD_ORI_ATE
      ,ORI_ATE.DS_ORI_ATE
      ,DOC.NM_USUARIO
      ,DOC.CD_DOCUMENTO "COD. DOCUMENTO"
      ,DOCUMENTO.DS_DOCUMENTO "DOCUMENTO"
      ,DOC.DT_REGISTRO "DATA"
      ,SUBSTR(TO_CHAR(DOC.DT_REGISTRO),10,20) AS HORARIO 
         
      ,Case
   
      when (DS_RESPOSTA = 'checked' and Ds_Pergunta = 'CVERDE') then 'VERDE'
      when (DS_RESPOSTA = 'checked' and Ds_Pergunta = 'CAMARELO') then 'AMARELO'
      when (DS_RESPOSTA = 'checked' and Ds_Pergunta = 'CVERMELHO') then 'VERMELHO'
      when (DS_RESPOSTA = 'checked' and Ds_Pergunta = 'CAZUL') then 'AZUL'
     
      else '' end STATUS, -- nunca esquecer do STATUS NAS TABELAS

          CASE  
          WHEN (DS_RESPOSTA = 'checked' and Ds_Pergunta = 'CVERDE' /*encontrar no descrição*/) THEN 1 END VERDE,
          CASE
          WHEN (DS_RESPOSTA = 'checked' and Ds_Pergunta = 'CAMARELO' /*encontrar no descrição*/) THEN 1 END AMARELO,
          CASE
          WHEN (DS_RESPOSTA = 'checked' and Ds_Pergunta = 'CVERMELHO' /*encontrar no descrição*/) THEN 1 END VERMELHO,
          CASE
          WHEN (DS_RESPOSTA = 'checked' and Ds_Pergunta = 'CAZUL' /*encontrar no descrição*/) THEN 1 END AZUL
                
FROM REGISTRO_DOCUMENTO DOC
INNER JOIN ATENDIME ATENDIME
  ON ATENDIME.CD_ATENDIMENTO = DOC.CD_ATENDIMENTO
INNER JOIN DOCUMENTO DOCUMENTO
  ON DOCUMENTO.CD_DOCUMENTO = DOC.CD_DOCUMENTO
INNER JOIN ORI_ATE ORI_ATE
  ON ORI_ATE.CD_ORI_ATE = ATENDIME.CD_ORI_ATE
INNER JOIN REGISTRO_RESPOSTA RESPOSTA
  ON RESPOSTA.CD_REGISTRO_DOCUMENTO = DOC.CD_REGISTRO_DOCUMENTO
INNER JOIN PERGUNTA_DOC PERGUNTA
  ON PERGUNTA.CD_PERGUNTA_DOC = RESPOSTA.CD_PERGUNTA_DOC

WHERE TO_CHAR(ATENDIME.DT_ATENDIMENTO,'DD/MM/YYYY' )= '30/06/2020'
AND ATENDIME.CD_ORI_ATE = '11'
AND DOC.SN_IMPRESSO NOT in ('C')
AND doc.cd_documento in ('180')
and RESPOSTA.ds_resposta = 'checked'
and RESPOSTA.cd_pergunta_doc IN ('40904','40905','40906','40907')
ORDER BY ATENDIME.CD_ATENDIMENTO
        ,DOC.DT_REGISTRO;
        
SELECT * FROM PERGUNTA_DOC;

---------------------- EDITANDO CORES SITUAÇÃO -----------------------------

SELECT 
       
       DOC.CD_REGISTRO_DOCUMENTO "REGISTRO"
      ,DOC.CD_ATENDIMENTO "ATENDIMENTO"
      ,to_char(DOC.DT_REGISTRO,'DD/MM/YYYY') "DATA"
      ,SUBSTR(TO_CHAR(DOC.DT_REGISTRO),10,20) AS HORARIO 
      
      ,Case
   
      when (DS_RESPOSTA = 'checked' and Ds_Pergunta = 'CVERDE') then 'VERDE'
      when (DS_RESPOSTA = 'checked' and Ds_Pergunta = 'CAMARELO') then 'AMARELO'
      when (DS_RESPOSTA = 'checked' and Ds_Pergunta = 'CVERMELHO') then 'VERMELHO'
      when (DS_RESPOSTA = 'checked' and Ds_Pergunta = 'CAZUL') then 'AZUL'
     
      else '' end STATUS -- nunca esquecer do STATUS NAS TABELAS
                   
FROM REGISTRO_DOCUMENTO DOC
INNER JOIN ATENDIME ATENDIME
  ON ATENDIME.CD_ATENDIMENTO = DOC.CD_ATENDIMENTO
INNER JOIN DOCUMENTO DOCUMENTO
  ON DOCUMENTO.CD_DOCUMENTO = DOC.CD_DOCUMENTO
INNER JOIN ORI_ATE ORI_ATE
  ON ORI_ATE.CD_ORI_ATE = ATENDIME.CD_ORI_ATE
INNER JOIN REGISTRO_RESPOSTA RESPOSTA
  ON RESPOSTA.CD_REGISTRO_DOCUMENTO = DOC.CD_REGISTRO_DOCUMENTO
INNER JOIN PERGUNTA_DOC PERGUNTA
  ON PERGUNTA.CD_PERGUNTA_DOC = RESPOSTA.CD_PERGUNTA_DOC

--WHERE ATENDIME.CD_ATENDIMENTO ='4519878'

WHERE TO_CHAR(ATENDIME.DT_ATENDIMENTO,'DD/MM/YYYY' )= '30/06/2020'
AND ATENDIME.CD_ORI_ATE = '11'
AND DOC.SN_IMPRESSO NOT in ('C')
AND doc.cd_documento in ('180','157','115')
and RESPOSTA.ds_resposta = 'checked'
and RESPOSTA.cd_pergunta_doc IN ('40904','40905','40906','40907')
ORDER BY ATENDIME.CD_ATENDIMENTO
        ,DOC.DT_REGISTRO;