/*
DEVELOPED BY SAMIRA ALVES LUCIO DIA
DATE: 01/07/2020
GOAL: REPORT DEVELOPED TO CALCULATE THE TIME BETWEEN PATIENT CARE DURIN CHILD EMERGENCY
*/

-----------------------------FUNCIONANDO SEM CLASSIFICAÇÃO -----------------------------------------------------------

SELECT
       DOC.CD_REGISTRO_DOCUMENTO "REGISTRO"
      ,DOC.CD_ATENDIMENTO "ATENDIMENTO"
      ,ATENDIME.CD_ORI_ATE
      ,ORI_ATE.DS_ORI_ATE
      ,DOC.NM_USUARIO
      ,DOC.CD_DOCUMENTO "COD. DOCUMENTO"
      ,DOCUMENTO.DS_DOCUMENTO "DOCUMENTO"
      ,to_char(DOC.DT_REGISTRO,'DD/MM/YYYY') "DIA"
      ,SUBSTR(TO_CHAR(DOC.DT_REGISTRO),10,20) AS HORARIO 
      ,CORES.STATUS
         
FROM REGISTRO_DOCUMENTO DOC
INNER JOIN ATENDIME ATENDIME
  ON ATENDIME.CD_ATENDIMENTO = DOC.CD_ATENDIMENTO
INNER JOIN DOCUMENTO DOCUMENTO
  ON DOCUMENTO.CD_DOCUMENTO = DOC.CD_DOCUMENTO
INNER JOIN ORI_ATE ORI_ATE
  ON ORI_ATE.CD_ORI_ATE = ATENDIME.CD_ORI_ATE
INNER JOIN VDIC_TRIAGEM_INFANTIL_COR CORES
  ON CORES.CD_ATENDIMENTO = DOC.CD_ATENDIMENTO
WHERE TO_CHAR(ATENDIME.DT_ATENDIMENTO,'DD/MM/YYYY' )= '30/06/2020'
AND ATENDIME.CD_ORI_ATE = '11'
AND DOC.SN_IMPRESSO NOT in ('C')
AND doc.cd_documento in ('180','157','115')
ORDER BY ATENDIME.CD_ATENDIMENTO,
         CORES.STATUS,
         HORARIO;
         
    --------------------------USANDO PARA TESTE DE CALCULO-----------------------------------------------


SELECT 
       
      DOC.CD_REGISTRO_DOCUMENTO "REGISTRO"
      ,DOC.CD_ATENDIMENTO "ATENDIMENTO"
      ,ATENDIME.CD_ORI_ATE
      ,ORI_ATE.DS_ORI_ATE
      ,DOC.NM_USUARIO
      ,DOC.CD_DOCUMENTO "COD. DOCUMENTO"
      ,DOCUMENTO.DS_DOCUMENTO "DOCUMENTO"
      ,DOC.DT_REGISTRO "DATA"
      ,SUBSTR(TO_CHAR(DOC.DT_REGISTRO),10,20) AS HORARIO 
         
FROM REGISTRO_DOCUMENTO DOC
INNER JOIN ATENDIME ATENDIME
ON ATENDIME.CD_ATENDIMENTO = DOC.CD_ATENDIMENTO
INNER JOIN DOCUMENTO DOCUMENTO
ON DOCUMENTO.CD_DOCUMENTO = DOC.CD_DOCUMENTO
INNER JOIN ORI_ATE ORI_ATE
ON ORI_ATE.CD_ORI_ATE = ATENDIME.CD_ORI_ATE
--WHERE ATENDIME.CD_ATENDIMENTO ='4519878'
WHERE TO_CHAR(ATENDIME.DT_ATENDIMENTO,'DD/MM/YYYY' )= '30/06/2020'
AND ATENDIME.CD_ORI_ATE = '11'
AND DOC.SN_IMPRESSO NOT in ('C')

ORDER BY ATENDIME.CD_ATENDIMENTO
        ,DOC.DT_REGISTRO;
