/*
DEVELOPED BY SAMIRA ALVES LUCIO DIA
DATE: 01/07/2020
GOAL: VDIC DEVELOPED TO MAKE A SEARCH INTO DOCUMENT TRIAGEM INFANTIL, SO IN THE 
REPORT FLUXO ATENDIMENTO WE ARE ABLE TO KNOW EACH PACIENT PRIORITY CLASSIFICATION
*/
CREATE OR REPLACE FORCE VIEW VDIC_TRIAGEM_INFANTIL_COR
(
   CD_REGISTRO_DOCUMENTO
  ,CD_ATENDIMENTO
  ,DIA
  ,HORARIO
  ,STATUS
  
)  AS
  SELECT 
       
       DOC.CD_REGISTRO_DOCUMENTO "REGISTRO"
      ,DOC.CD_ATENDIMENTO "ATENDIMENTO"
      ,to_char(DOC.DT_REGISTRO,'DD/MM/YYYY') "DIA"
      ,SUBSTR(TO_CHAR(DOC.DT_REGISTRO),10,20) AS HORARIO 
      
      ,Case
   
      when (DS_RESPOSTA = 'checked' and Ds_Pergunta = 'CVERDE') then 'VERDE'
      when (DS_RESPOSTA = 'checked' and Ds_Pergunta = 'CAMARELO') then 'AMARELO'
      when (DS_RESPOSTA = 'checked' and Ds_Pergunta = 'CVERMELHO') then 'VERMELHO'
      when (DS_RESPOSTA = 'checked' and Ds_Pergunta = 'CAZUL') then 'AZUL'
     
      else '' end STATUS -- nunca esquecer do STATUS NAS TABELAS
                   
FROM REGISTRO_DOCUMENTO DOC
INNER JOIN ATENDIME ATENDIME
  ON ATENDIME.CD_ATENDIMENTO = DOC.CD_ATENDIMENTO
INNER JOIN DOCUMENTO DOCUMENTO
  ON DOCUMENTO.CD_DOCUMENTO = DOC.CD_DOCUMENTO
INNER JOIN ORI_ATE ORI_ATE
  ON ORI_ATE.CD_ORI_ATE = ATENDIME.CD_ORI_ATE
INNER JOIN REGISTRO_RESPOSTA RESPOSTA
  ON RESPOSTA.CD_REGISTRO_DOCUMENTO = DOC.CD_REGISTRO_DOCUMENTO
INNER JOIN PERGUNTA_DOC PERGUNTA
  ON PERGUNTA.CD_PERGUNTA_DOC = RESPOSTA.CD_PERGUNTA_DOC

--WHERE ATENDIME.CD_ATENDIMENTO ='4519878'
--WHERE TO_CHAR(ATENDIME.DT_ATENDIMENTO,'DD/MM/YYYY' )= '30/06/2020'
WHERE ATENDIME.CD_ORI_ATE = '11'
AND DOC.SN_IMPRESSO NOT in ('C')
AND doc.cd_documento in ('180')
and RESPOSTA.ds_resposta = 'checked'
and RESPOSTA.cd_pergunta_doc IN ('40904','40905','40906','40907')

/


GRANT DELETE ON VDIC_TRIAGEM_INFANTIL_COR TO mv2000
/
GRANT INSERT ON VDIC_TRIAGEM_INFANTIL_COR TO mv2000
/
GRANT SELECT ON VDIC_TRIAGEM_INFANTIL_COR TO mv2000
/
GRANT UPDATE ON VDIC_TRIAGEM_INFANTIL_COR TO mv2000
/
GRANT DELETE ON VDIC_TRIAGEM_INFANTIL_COR TO dbasgu
/
GRANT INSERT ON VDIC_TRIAGEM_INFANTIL_COR TO dbasgu
/
GRANT SELECT ON VDIC_TRIAGEM_INFANTIL_COR TO dbasgu
/
GRANT UPDATE ON VDIC_TRIAGEM_INFANTIL_COR TO dbasgu
/
GRANT DELETE ON VDIC_TRIAGEM_INFANTIL_COR TO mvintegra
/
GRANT INSERT ON VDIC_TRIAGEM_INFANTIL_COR TO mvintegra
/
GRANT SELECT ON VDIC_TRIAGEM_INFANTIL_COR TO mvintegra
/
GRANT UPDATE ON VDIC_TRIAGEM_INFANTIL_COR TO mvintegra
/
GRANT DELETE ON VDIC_TRIAGEM_INFANTIL_COR TO dbaps
/
GRANT INSERT ON VDIC_TRIAGEM_INFANTIL_COR TO dbaps
/
GRANT SELECT ON VDIC_TRIAGEM_INFANTIL_COR TO dbaps
/
GRANT UPDATE ON VDIC_TRIAGEM_INFANTIL_COR TO dbaps
/